version: '3.7'

services:
  app:
    container_name: adm_videos_app
    build: .
    profiles: ["app"]
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - rabbit
    networks:
      - adm_videos_network

  mysql:
    container_name: adm_videos_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_videos
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - adm_videos_network

  rabbit:
    container_name: adm_videos_rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=adm_videos
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - adm_videos_network

networks:
  adm_videos_network: