version: '3.7'

services:
  app:
    container_name: adm_videos_app
#    image: deploydesexta/fc3-admin-catalogo-de-videos-java:modulos_29_ci-cd-2
    build:
      context: ../../
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - 8080:8080
    networks:
      - adm_videos_network
      - adm_videos_services
    depends_on:
      - filebeat
    labels:
      filebeat_collector: true
    extra_hosts:
      - "keycloak.internal:127.0.0.1"

  filebeat:
    container_name: adm_videos_filebeat
    image: docker.elastic.co/beats/filebeat:7.17.9
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - ../.docker/filebeat:/usr/share/filebeat/data:rw                    # Persistence data
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
    networks:
      - adm_videos_network
      - elastic

networks:
  adm_videos_network:
  adm_videos_services:
    external: true
  elastic:
    external: true