name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'hotfix/**'
      - 'release/**'
      - 'modulos/**'
  workflow_dispatch:

env:
  IMAGE_NAME: deploydesexta/fc3-admin-catalogo-de-videos-java

jobs:
  # Job para a execução dos testes
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    # Configuração de passos do nosso job
    steps:
      # 1. Check-out do código fonte
      - uses: actions/checkout@v3
      # 2. Configurar a JDK na máquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3. Executar os testes da aplicação
      - name: Run application tests
        run: ./gradlew test

  # Job para buildar a aplicação
  build:
    name: Build runner
    needs: tests
    runs-on: ubuntu-latest
    # Configuração de passos do nosso job
    steps:
      # 1. Check-out do código fonte
      - uses: actions/checkout@v3
      # 2. Configurar a JDK na máquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3. Valida a existência do gradle wrapper
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      # 4. Realizar o build para gerar o artefato final
      - name: Build da aplicação
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build -x test
      # 5. Definir a variavel branch name
      - name: Set BUILD_TAG
        run: |
          echo BUILD_TAG=$(echo ${{ github.head_ref || github.ref_name }} | sed "s,/,_,g")-${{ github.run_number }} >> $GITHUB_ENV
      # 6. Print BUILD_TAG
      - name: Print BUILD_TAG defined
        run: |
          echo "Branch     ---> ${{ github.head_ref || github.ref_name }}"
          echo "Run number ---> ${{ github.run_number }}"
          echo "Tag        ---> ${{ env.BUILD_TAG }}"
      # 7. Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      # 8. Build & Deploy da imagem
      - name: Build & push da imagem do docker
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: VERSION=${{ env.BUILD_TAG }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}