name: CI Pipeline

on:
  push:
  # Habilita o gatilho manual através da interface do Github Actions
  workflow_dispatch:

jobs:
  # Job para a execução dos testes
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    # Configuração de passos do nosso job
    steps:
      # 1. Check-out do código fonte
      - uses: actions/checkout@v3
      # 2. Configurar a JDK na máquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3. Executar os testes da aplicação
      - name: Run application tests
        run: ./gradlew test