name: CI Pipeline

on:
  push:
    branches:
      - 'bugfix/*'
      - 'feature/*'
      - 'hotfix/*'
      - 'modulos/*'
    # Habilita o disparo manual através do página do Github Actions
    workflow_dispatch:

# Permissões da nossa pipeline
permissions:
  contents: read
  pull-requests: read

jobs:
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    # Configuração dos passos que compõem o job
    steps:
      # 1. Faz o download do repositório
      - uses: actions/checkout@v3
      # 2. Configurar a JDK na máquina
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3. Executar os testes
      - name: Run tests
        run: ./gradlew test